language: cpp
dist: trusty
sudo: false
script: make
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - cmake
    - boost
